name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: hseeberger/scala-sbt:8u222_1.3.10_2.13.1

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt test
